# Custom Language File for Launcher Customizer

[ejs.app]
title = "HideOut Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/Zepep/HideOut"
mediaXURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/letemple"

[ejs.settings]
sourceGithubLink = "https://github.com/Zepep/HideOut"
supportLink = "https://github.com/Zepep/HideOut/issues"

[ejs.welcome]
welcomeHeader = "BIENVENUE SUR HIDEOUT"
welcomeDescription = "HideOut est un projet que j’ai construit seul, avec une seule idée en tête : offrir une aventure Cobblemon unique, soignée et immersive. Basé sur le modpack CobbleVerse, le serveur vous plonge dans un monde sur mesure, entre exploration, stratégie et collection. Chaque région, chaque biome, chaque défi a été pensé pour offrir une vraie sensation d’aventure dans un univers cohérent et vivant."
welcomeDescCTA = "Quelques clics vous séparent du monde de HideOut."


