[ejs.landing]
updateAvailableTooltip = "Mise à jour disponible"
usernamePlaceholder = "Nom d'utilisateur"
usernameEditButton = "Modifier"
settingsTooltip = "Paramètres"
serverStatus = "SERVEUR"
serverStatusPlaceholder = "HORS LIGNE"
mojangStatus = "STATUT MOJANG"
mojangStatusTooltipTitle = "Services"
mojangStatusNETitle = "Non essentiel"
newsButton = "ACTUALITÉS"
launchButton = "JOUER"
launchButtonPlaceholder = "&#8226; Aucun serveur sélectionné"
launchDetails = "Veuillez patienter..."
newsNavigationStatus = "{currentPage} sur {totalPages}"
newsErrorLoadSpan = "Vérification des actualités..."
newsErrorFailedSpan = "Échec du chargement des actualités"
newsErrorRetryButton = "Réessayer"
newsErrorNoneSpan = "Aucune actualité"

[ejs.login]
loginCancelText = "Annuler"
loginSubheader = "CONNEXION MINECRAFT"
loginEmailError = "* Valeur invalide"
loginEmailPlaceholder = "EMAIL OU NOM D'UTILISATEUR"
loginPasswordError = "* Requis"
loginPasswordPlaceholder = "MOT DE PASSE"
loginForgotPasswordLink = "https://minecraft.net/password/forgot/"
loginForgotPasswordText = "mot de passe oublié ?"
loginRememberMeText = "se souvenir de moi ?"
loginButtonText = "CONNEXION"
loginNeedAccountLink = "https://minecraft.net/store/minecraft-java-edition/"
loginNeedAccountText = "Besoin d’un compte ?"
loginPasswordDisclaimer1 = "Votre mot de passe est envoyé directement à Mojang et n’est jamais stocké."
loginPasswordDisclaimer2 = "{appName} n’est pas affilié à Mojang AB."

[ejs.loginOptions]
loginOptionsTitle = "Options de connexion"
loginWithMicrosoft = "Connexion avec Microsoft"
loginWithMojang = "Connexion avec Mojang"
cancelButton = "Annuler"

[ejs.overlay]
serverSelectHeader = "Serveurs disponibles"
serverSelectConfirm = "Sélectionner"
serverSelectCancel = "Annuler"
accountSelectHeader = "Sélectionner un compte"
accountSelectConfirm = "Sélectionner"
accountSelectCancel = "Annuler"

[ejs.settings]
navHeaderText = "Paramètres"
navAccount = "Compte"
navMinecraft = "Minecraft"
navMods = "Mods"
navJava = "Java"
navLauncher = "Launcher"
navAbout = "À propos"
navUpdates = "Mises à jour"
navDone = "Terminé"
tabAccountHeaderText = "Paramètres du compte"
tabAccountHeaderDesc = "Ajoutez ou gérez vos comptes."
microsoftAccount = "Microsoft"
addMicrosoftAccount = "+ Ajouter un compte Microsoft"
mojangAccount = "Mojang"
addMojangAccount = "+ Ajouter un compte Mojang"
minecraftTabHeaderText = "Paramètres Minecraft"
minecraftTabHeaderDesc = "Options liées au lancement du jeu."
gameResolutionTitle = "Résolution du jeu"
launchFullscreenTitle = "Lancer en plein écran."
autoConnectTitle = "Connexion automatique au serveur HideOut au lancement."
launchDetachedTitle = "Lancer le jeu séparément du launcher."
launchDetachedDesc = "Si le jeu n’est pas détaché, fermer le launcher fermera aussi le jeu."
tabModsHeaderText = "Paramètres des mods"
tabModsHeaderDesc = "Activer ou désactiver les mods."
switchServerButton = "Changer"
requiredMods = "Mods obligatoires"
optionalMods = "Mods facultatifs"
dropinMods = "Mods supplémentaires"
addMods = "Ajouter des mods"
dropinRefreshNote = "(F5 pour actualiser)"
shaderpacks = "Shaders"
shaderpackDesc = "Activez ou désactivez les shaders. Nécessite un bon PC. Vous pouvez ajouter vos packs ici."
selectShaderpack = "Sélectionner un shader"
tabJavaHeaderText = "Paramètres Java"
tabJavaHeaderDesc = "Gérez la configuration Java (avancé)."
memoryTitle = "Mémoire"
maxRAM = "RAM maximale"
minRAM = "RAM minimale"
memoryDesc = "La RAM minimale recommandée est de 3 Go. Fixer la RAM min et max au même niveau peut réduire les lags."
memoryTotalTitle = "Total"
memoryAvailableTitle = "Disponible"
javaExecutableTitle = "Exécutable Java"
javaExecSelDialogTitle = "Sélectionner l’exécutable Java"
javaExecSelButtonText = "Choisir un fichier"
javaExecDesc = "L'exécutable Java est vérifié avant le lancement."
javaPathDesc = "Le chemin doit se terminer par <strong>{pathSuffix}</strong>."
jvmOptsTitle = "Options JVM supplémentaires"
jvmOptsDesc = "Options pour la JVM au lancement. Ne pas inclure <em>-Xms</em> ni <em>-Xmx</em>."
launcherTabHeaderText = "Paramètres du launcher"
launcherTabHeaderDesc = "Options liées au launcher HideOut."
allowPrereleaseTitle = "Autoriser les versions pré-release."
allowPrereleaseDesc = "Ces versions incluent des nouveautés encore instables.<br>Cela sera toujours vrai si vous utilisez une version pré-release."
dataDirectoryTitle = "Répertoire des données"
selectDataDirectory = "Sélectionner un dossier"
chooseFolder = "Choisir un dossier"
dataDirectoryDesc = "Tous les fichiers du jeu et les installations Java locales seront stockés ici.<br>Les screenshots et mondes sont enregistrés dans le dossier d’instance correspondant au serveur."
aboutTabHeaderText = "À propos"
aboutTabHeaderDesc = "Infos et notes de version de HideOut."
aboutTitle = "{appName}"
stableRelease = "Version stable"
versionText = "Version "
sourceGithub = "Code source (GitHub)"
support = "Support"
devToolsConsole = "Console DevTools"
releaseNotes = "Notes de version"
changelog = "Journal des modifications"
noReleaseNotes = "Aucune note disponible"
viewReleaseNotes = "Voir les notes sur GitHub"
launcherUpdatesHeaderText = "Mises à jour du launcher"
launcherUpdatesHeaderDesc = "Téléchargez et installez les mises à jour du launcher HideOut."
checkForUpdates = "Vérifier les mises à jour"
whatsNew = "Nouveautés"
updateReleaseNotes = "Notes de mise à jour"

[ejs.waiting]
waitingText = "En attente de Microsoft..."

[ejs.welcome]
continueButton = "CONTINUER"

[js.discord]
waiting = "En attente du client..."
state = "Serveur : {shortId}"

[js.index]
microsoftLoginTitle = "Connexion Microsoft"
microsoftLogoutTitle = "Déconnexion Microsoft"

[js.login]
login = "CONNEXION"
loggingIn = "CONNEXION EN COURS"
success = "SUCCÈS"
tryAgain = "Réessayer"

[js.login.error]
invalidValue = "* Valeur invalide"
requiredValue = "* Requis"

[js.login.error.unknown]
title = "Erreur inconnue à la connexion"
desc = "Une erreur inconnue s’est produite. Veuillez consulter la console pour plus de détails."

[js.landing.launch]
pleaseWait = "Veuillez patienter..."
failureTitle = "Erreur au lancement"
failureText = "Voir la console (CTRL + Maj + i) pour plus de détails."
okay = "OK"

[js.landing.selectedAccount]
noAccountSelected = "Aucun compte sélectionné"

[js.landing.selectedServer]
noSelection = "Aucun serveur sélectionné"
loading = "Chargement..."

[js.landing.serverStatus]
server = "SERVEUR"
offline = "HORS LIGNE"
players = "JOUEURS"

[js.landing.systemScan]
checking = "Analyse du système..."
noCompatibleJava = "Aucune installation Java<br>compatible trouvée"
installJavaMessage = "Pour lancer Minecraft, une version Java 64 bits {major} est requise. Voulez-vous qu’on l’installe ?"
installJava = "Installer Java"
installJavaManually = "Installer manuellement"
javaDownloadPrepare = "Préparation du téléchargement de Java..."
javaDownloadFailureTitle = "Erreur pendant le téléchargement de Java"
javaDownloadFailureText = "Voir la console (CTRL + Maj + i) pour plus de détails."
javaRequired = "Java est requis<br>pour lancer"
javaRequiredMessage = 'Une version Java x64 {major} valide est requise.<br><br>Consultez notre <a href="https://github.com/dscalzi/HeliosLauncher/wiki/Java-Management#manually-installing-a-valid-version-of-java">guide d’installation Java</a> pour l’installer manuellement.'
javaRequiredDismiss = "J’ai compris"
javaRequiredCancel = "Retour"

[js.landing.downloadJava]
findJdkFailure = "Échec de la détection d’une distribution OpenJDK."
javaDownloadCorruptedError = "Le JDK téléchargé est corrompu (empreinte invalide)."
extractingJava = "Extraction de Java"
javaInstalled = "Java installé !"

[js.landing.dlAsync]
loadingServerInfo = "Chargement des infos serveur..."
fatalError = "Erreur fatale"
unableToLoadDistributionIndex = "Impossible de charger l’index de distribution. Voir la console (CTRL + Maj + i)."
pleaseWait = "Veuillez patienter..."
errorDuringLaunchTitle = "Erreur au lancement"
seeConsoleForDetails = "Voir la console (CTRL + Maj + i) pour plus de détails."
validatingFileIntegrity = "Validation de l’intégrité des fichiers..."
errorDuringFileVerificationTitle = "Erreur lors de la vérification des fichiers"
downloadingFiles = "Téléchargement des fichiers..."
errorDuringFileDownloadTitle = "Erreur pendant le téléchargement"
preparingToLaunch = "Préparation du lancement..."
launchingGame = "Lancement du jeu..."
launchWrapperNotDownloaded = "Le fichier principal, LaunchWrapper, n’a pas pu être téléchargé correctement.<br><br>Désactivez temporairement votre antivirus et relancez le jeu.<br><br>Si vous avez un moment, <a href=\"https://github.com/Zepep/HideOut/issues\">signalez le problème</a> en précisant le nom de votre antivirus."
doneEnjoyServer = "C’est prêt. Bon jeu sur le serveur HideOut !"
checkConsoleForDetails = "Voir la console (CTRL + Maj + i) pour plus de détails."

[js.landing.news]
checking = "Vérification des actualités..."

[js.landing.discord]
loading = "Chargement du jeu..."
joining = "Connexion à HideOut..."
joined = "Connecté au monde !"

[js.overlay]
dismiss = "Fermer"

[js.settings.fileSelectors]
executables = "Fichiers exécutables"
allFiles = "Tous les fichiers"

[js.settings.mstfLogin]
errorTitle = "Une erreur est survenue"
errorMessage = "L'authentification Microsoft a échoué. Veuillez réessayer."
okButton = "OK"

[js.settings.mstfLogout]
errorTitle = "Une erreur est survenue"
errorMessage = "La déconnexion Microsoft a échoué. Veuillez réessayer."
okButton = "OK"

[js.settings.authAccountSelect]
selectButton = "Sélectionner un compte"
selectedButton = "Compte sélectionné &#10004;"

[js.settings.authAccountLogout]
lastAccountWarningTitle = "Attention<br>Ceci est votre dernier compte"
lastAccountWarningMessage = "Pour utiliser le launcher HideOut, vous devez être connecté à au moins un compte. Vous devrez vous reconnecter après.<br><br>Voulez-vous vraiment vous déconnecter ?"
confirmButton = "Oui, je confirme"
cancelButton = "Annuler"

[js.settings.authAccountPopulate]
username = "Nom d'utilisateur"
uuid = "UUID"
selectAccount = "Sélectionner un compte"
selectedAccount = "Compte sélectionné ✓"
logout = "Déconnexion"

[js.settings.dropinMods]
removeButton = "Supprimer"
deleteFailedTitle = "Échec de suppression<br>du mod {fullName}"
deleteFailedMessage = "Assurez-vous que le fichier n’est pas utilisé et réessayez."
failedToggleTitle = "Échec d’activation<br>d’un ou plusieurs mods"
okButton = "OK"

[js.settings.serverListing]
mainServer = "Serveur principal"

[js.settings.java]
selectedJava = "Sélectionné : Java {version} ({vendor})"
invalidSelection = "Sélection invalide"
requiresJava = "Nécessite Java {major} x64."
availableOptions = "Options disponibles pour Java {major} (HotSpot VM)"

[js.settings.about]
preReleaseTitle = "Pré-version"
stableReleaseTitle = "Version stable"
releaseNotesFailed = "Échec du chargement des notes de version."

[js.settings.updates]
newReleaseTitle = "Nouvelle version disponible"
newPreReleaseTitle = "Nouvelle pré-version disponible"
downloadingButton = "Téléchargement..."
downloadButton = 'Télécharger depuis GitHub<span style="font-size: 10px;color: gray;text-shadow: none !important;">Fermez le launcher puis exécutez le .dmg pour mettre à jour.</span>'
latestVersionTitle = "Vous utilisez la dernière version"
checkForUpdatesButton = "Vérifier les mises à jour"
checkingForUpdatesButton = "Vérification des mises à jour..."

[js.settings.msftLogin]
errorTitle = "Échec de la connexion Microsoft"
errorMessage = "Impossible d’authentifier votre compte Microsoft. Veuillez réessayer."
okButton = "OK"

[js.uibinder.startup]
fatalErrorTitle = "Erreur fatale : échec du chargement de l’index"
fatalErrorMessage = "Impossible de se connecter aux serveurs pour télécharger l’index de distribution. Aucune copie locale disponible.<br><br>L’index de distribution est essentiel pour récupérer les dernières infos serveur. Assurez-vous d’être connecté à Internet puis relancez le launcher HideOut."
closeButton = "Fermer"

[js.uibinder.validateAccount]
failedMessageTitle = "Échec du rafraîchissement de la session"
failedMessage = "Impossible de rafraîchir la session de <strong>{account}</strong>. Veuillez choisir un autre compte ou vous reconnecter."
failedMessageSelectAnotherAccount = "Impossible de rafraîchir la session de <strong>{account}</strong>. Veuillez vous reconnecter."
loginButton = "Connexion"
selectAnotherAccountButton = "Choisir un autre compte"

[js.uicore.autoUpdate]
checkingForUpdateButton = "Vérification des mises à jour..."
installNowButton = "Installer maintenant"
checkForUpdatesButton = "Vérifier les mises à jour"

[js.auth.microsoft.error]
noProfileTitle = "Erreur à la connexion :<br>Profil non configuré"
noProfileDesc = "Votre compte Microsoft ne possède pas encore de profil Minecraft. Si vous venez d’acheter le jeu ou de l'activer via Xbox Game Pass, vous devez configurer votre profil sur <a href=\"https://minecraft.net/\">Minecraft.net</a>.<br><br>Si vous n’avez pas encore acheté le jeu, vous pouvez également le faire sur <a href=\"https://minecraft.net/\">Minecraft.net</a>."
noXboxAccountTitle = "Erreur à la connexion :<br>Pas de compte Xbox"
noXboxAccountDesc = "Votre compte Microsoft n’est pas lié à un compte Xbox."
xblBannedTitle = "Erreur à la connexion :<br>Xbox Live indisponible"
xblBannedDesc = "Votre compte Microsoft est associé à un pays où Xbox Live est indisponible ou interdit."
under18Title = "Erreur à la connexion :<br>Autorisation parentale requise"
under18Desc = "Les comptes de moins de 18 ans doivent être ajoutés à une famille par un adulte."
unknownTitle = "Erreur inconnue à la connexion"
unknownDesc = "Une erreur inconnue est survenue. Veuillez consulter la console pour plus de détails."

[js.auth.mojang.error]
methodNotAllowedTitle = "Erreur interne :<br>Méthode non autorisée"
methodNotAllowedDesc = "Méthode non autorisée. Veuillez signaler cette erreur."
notFoundTitle = "Erreur interne :<br>Non trouvé"
notFoundDesc = "Le point d’authentification est introuvable. Veuillez signaler ce problème."
accountMigratedTitle = "Erreur à la connexion :<br>Compte migré"
accountMigratedDesc = "Vous avez tenté de vous connecter avec un compte migré. Essayez avec votre adresse email comme identifiant."
invalidCredentialsTitle = "Erreur à la connexion :<br>Identifiants invalides"
invalidCredentialsDesc = "L’email ou le mot de passe saisi est incorrect. Veuillez réessayer."
tooManyAttemptsTitle = "Erreur à la connexion :<br>Trop de tentatives"
tooManyAttemptsDesc = "Trop de tentatives de connexion ont été effectuées récemment. Veuillez réessayer plus tard."
invalidTokenTitle = "Erreur à la connexion :<br>Jeton invalide"
invalidTokenDesc = "Le jeton d’accès fourni est invalide."
tokenHasProfileTitle = "Erreur à la connexion :<br>Jeton lié à un profil"
tokenHasProfileDesc = "Le jeton d’accès est déjà lié à un profil. La sélection de profil n’est pas encore implémentée."
credentialsMissingTitle = "Erreur à la connexion :<br>Identifiants manquants"
credentialsMissingDesc = "Le nom d'utilisateur/mot de passe est manquant ou le mot de passe fait moins de 3 caractères."
invalidSaltVersionTitle = "Erreur à la connexion :<br>Version de sel invalide"
invalidSaltVersionDesc = "Version de sel invalide."
unsupportedMediaTypeTitle = "Erreur interne :<br>Type non pris en charge"
unsupportedMediaTypeDesc = "Type de média non pris en charge. Veuillez signaler cette erreur."
accountGoneTitle = "Erreur à la connexion :<br>Compte migré"
accountGoneDesc = "Ce compte a été migré vers Microsoft. Connectez-vous via Microsoft."
unreachableTitle = "Erreur à la connexion :<br>Serveurs inaccessibles"
unreachableDesc = "Impossible de contacter les serveurs d’authentification. Vérifiez votre connexion Internet."
gameNotPurchasedTitle = "Erreur à la connexion :<br>Jeu non acheté"
gameNotPurchasedDesc = "Le compte que vous essayez d’utiliser n’a pas acheté Minecraft. Vous pouvez l’acheter sur <a href=\"https://minecraft.net/\">Minecraft.net</a>."
unknownErrorTitle = "Erreur inconnue à la connexion"
unknownErrorDesc = "Une erreur inconnue est survenue. Veuillez consulter la console pour plus de détails."
